apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-dp
  labels:
    estado: "1"
spec:
  selector: #permite seleccionar un conjunto de objetos que cumplan las condicione
    matchLabels:
      app: db
  replicas: 4 # indica al controlador que ejecute 2 pods
  template: # Plantilla que define los containers
    metadata:
      labels:
        app: db
    spec:
      volumes:
        - name: be-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      containers:
        - name: mysql-ait
          image: mysql:5.7
          env:
            - name: MYSQL_HOST
              value: localhost
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: namedb
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: be-storage
              mountPath: /var/lib/mysql
