apiVersion: apps/v1
kind: Deployment
metadata:
  name: ait-api
  labels:
    estado: "1"
spec:
  selector: #permite seleccionar un conjunto de objetos que cumplan las condicione
    matchLabels:
      app: api-be
  replicas: 4 # indica al controlador que ejecute 2 pods
  template: # Plantilla que define los containers
    metadata:
      labels:
        app: api-be
    spec:
      containers:
        - name: api-django
          image: farguello1995/ait_prueba_kubernetes
          env:
            - name: HOST_DB
              value: "db-service"
            - name: PORT_DB
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: portdb
            - name: USER_DB
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: username
            - name: PASSWORD_DB
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
            - name: NAME_DB
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: namedb
          ports:
            - containerPort: 9000
