apiVersion: v1
kind: Service
metadata:
  name: ait-svc
  labels:
     app: api-be
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30080
    protocol: TCP
  selector:
     app: api-be